[package]
name = "lilgrad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
arrow = "29.0.0"
tensor-rs = "0.5.9"
bytemuck = "1.12.3"
